### ISSUE TITLE
Consider adding cli flash support

### ISSUE THREAD

**Issue by jedahan** [lantern-works/pi-maker#2]
Etcher is frickin awesome, but sometimes you want to flash from the commandline. Luckily there is [an experimental etcher cli](https://etcher.io/cli/).

In addition, the [hypriot/flash](https://github.com/hypriot/flash) project looks promising as well.

Perhaps just a Makefile entry that would allow `make flash` and check for either cli and do the magic?

**Comment by westlane** [comment]
This is a great idea. We started with [hypriot/flash](https://github.com/hypriot/flash) and cloud-init earlier this year and moved on to the Etcher GUI for simplicity and access by non-technical folks. 

I've updated the README with instructions on how to leverage Etcher CLI: fdfd7a64410baa46824f177fb07ed80664d952e8

Because the operation requires special permission / confirmation and can be destructive (read: writes over an existing disk) I am reluctant to place directly into the makefile (for now). The README should help get started with this option by showing users how to directly invoke the "etcher" command.

**Comment by jedahan** [comment]
If you have time to share what was good and bad about flash and cloud-init, I'd love to hear it, especially on https://github.com/baculus-buoy/baculus/issues/10 

I was thinking of porting my build scripts over to that system. I thought it would be easier having all config in one file, but I haven't used those solutions yet.

Would you be open to a PR with `make flash` or `make etch` to run `sudo etcher ./share/build/rpi.img` ?
